name: project_backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  alfred: ^0.1.7
  postgres: ^2.6.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
